name: brainwavesocialapp
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.2
  json_annotation: ^4.9.0
  google_sign_in: ^6.2.1
  firebase_cloud_firestore: ^4.17.3
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
